name: paystack_flutter
description: "Paystack Flutter SDK."
version: 0.0.1
homepage: https://github.com/PaystackOSS/paystack_flutter

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.2

flutter:
  plugin:
    platforms:
      android:
        package: com.paystack.paystack_flutter
        pluginClass: PaystackFlutterPlugin
      ios:
        pluginClass: PaystackFlutterPlugin